### ISSUE TITLE
Compitable with ic_cdk 0.4.0

### ISSUE THREAD

**Issue by Myse1f** [Psychedelic/ic-kit#2]
I found that ic_cdk 0.4.0 deprecate `block_on` function and use its own [spawn](https://docs.rs/ic-cdk/latest/ic_cdk/fn.spawn.html).

`ic_kit` use `ic_cdk::block_on` to do the job of `ic::spwan`. 

Besides, `ic_cdk::spawn` doesn't need `Send` trait bound to the `future F` while `ic_kit` does. 
```rust
#[inline(always)]
pub fn spawn<F: 'static + std::future::Future<Output = ()> + std::marker::Send>(future: F) {
    get_context().spawn(future)
}
```

When I have a job which call another canister, the future returned does not have `Send` trait.  Thus `ic::spawn` can not execute the job.
```
    |
498 |     let xtc_balance: (Nat, ) = ic::call(Principal::from_text(XTC).unwrap(), "balanceOf", (ic::id(),))
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ await occurs here on type `Pin<Box<dyn Future<Output = Result<(ic_kit::candid::Nat,), (RejectionCode, std::string::String)>>>>`, which is not `Send`
note: required by a bound in `ic_kit::ic::spawn`


    |
555 |     ic::spawn(schedule_job());
    |     ^^^^^^^^^ future returned by `schedule_job` is not `Send`
    |
```

**Comment by qti3e** [comment]
Already fixed by yourself! #3
