### ISSUE TITLE
What is the motivation for this library?

### ISSUE THREAD

**Issue by seniorjoinu** [Psychedelic/ic-kit#4]
I see that there is something interesting with cycles going on, but I can't quite put my finger on it. Could you elaborate on it, please?

**Comment by qti3e** [comment]
Hi, sorry for the late reply, we usually do this discussions on our discord. This library is used as a replacement for IC CDK that offers mock implementation for Internet Computer System APIs which makes it possible to test a canister's logic on non-wasm targets, or in other words use `cargo test` to test the entire canister.
